services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-finly}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-finly}"]
      interval: 2s
      timeout: 5s
      retries: 30

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 30

  qdrant:
    image: qdrant/qdrant:v1.15
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/collections"]
      interval: 2s
      timeout: 3s
      retries: 60

  # одноразовый сервис для миграций
  migrate:
    image: finly-backend:latest
    entrypoint: ""
    command: [ "python", "backend/manage.py", "migrate", "--noinput" ]
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/finly}
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    restart: "no"


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: finly-backend:latest
    entrypoint: ""       # игнорируем ENTRYPOINT из Dockerfile
    command: ["python", "backend/manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/finly}
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"

  worker:
    image: finly-backend:latest
    entrypoint: ""
    command: ["python", "-m", "celery", "-A", "config", "worker", "-l", "info"]
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/finly}
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  beat:
    image: finly-backend:latest
    entrypoint: ""
    command: ["python", "-m", "celery", "-A", "config", "beat", "-l", "info", "-S", "django"]
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/finly}
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  db_data:
  qdrant_data:
