services:
  db:
    image: postgres:16
    container_name: finly_db
    environment:
      POSTGRES_USER: finly
      POSTGRES_PASSWORD: finly
      POSTGRES_DB: finly
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./main_db_script.sql:/docker-entrypoint-initdb.d/01_main_db_script.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finly"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finly_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DATABASE_URL: "postgresql://finly:finly@db:5432/finly"
      CORS_ALLOW_ALL_ORIGINS: "true"
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app/backend
    command: ["/entrypoint.sh"]

  redis:
    image: redis:7-alpine
    container_name: finly_redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finly_worker
    depends_on:
      - db
      - redis
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DATABASE_URL: "postgresql://finly:finly@db:5432/finly"
      CORS_ALLOW_ALL_ORIGINS: "true"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      QDRANT_URL: "http://qdrant:6333"
    command: ["bash", "-lc", "celery -A config worker -l info"]
    volumes:
      - ./backend:/app/backend

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finly_beat
    depends_on:
      - db
      - redis
    environment:
      DJANGO_DEBUG: "true"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      DATABASE_URL: "postgresql://finly:finly@db:5432/finly"
      CORS_ALLOW_ALL_ORIGINS: "true"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/1"
      QDRANT_URL: "http://qdrant:6333"
    command: ["bash", "-lc", "celery -A config beat -l info"]
    volumes:
      - ./backend:/app/backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: finly_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  db_data:
  qdrant_data:

