services:
  web:
    build:
      context: .
    working_dir: /app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpass
    depends_on:
      - database
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres:16-alpine
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend/smartfin-front:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"
    depends_on:
      - web

volumes:
  pgdata:
